version: '3.1'

services:
  springboot:
    image: dasoju/spring-boot-mongo-docker
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=dasoju
    - MONGO_DB_PASSWORD=96321
    ports:
    - 8200:8080
    networks:
    - flipkartnetwork
  mongo:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=dasoju
    - MONGO_INITDB_ROOT_PASSWORD=96321
    volumes:
    - mongodb:/data/db
    networks:
    - flipkartnetwork

volumes:
  mongodb:
    driver: local

networks:
  flipkartnetwork:
